Override ode to enable double precision
Ubuntu builds ode with double precision (see [^1]), we should do the same. Otherwise,
we get errors like the following in {lyrical,rolling}.gz-physics-vendor:

    In file included from /nix/store/0a944vkfl89hk2kzz36n5ywf8mgakr94-eigen-3.4.1/include/eigen3/Eigen/Core:296,
                     from /nix/store/0a944vkfl89hk2kzz36n5ywf8mgakr94-eigen-3.4.1/include/eigen3/Eigen/Dense:1,
                     from /nix/store/pnvgarfpkv5mz6i75bn77xjf3v7nhi0w-ros-lyrical-gz-dartsim-vendor-0.1.3-r3/include/dart/collision/CollisionObject.hpp:40,
                     from /build/gz_physics_vendor-release-release-lyrical-gz_physics_vendor-0.4.6-1/build/gz_physics_vendor-prefix/src/gz_physics_vendor/dartsim/src/GzCollisionDetector.cc:23:
    /nix/store/0a944vkfl89hk2kzz36n5ywf8mgakr94-eigen-3.4.1/include/eigen3/Eigen/src/Core/Matrix.h: In instantiation of
    'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = float [4]; _Scalar =
    double; int _Rows = 3; int _Cols = 1; int _Options = 0; int _MaxRows = 3; int _MaxCols = 1]':
    /build/gz_physics_vendor-release-release-lyrical-gz_physics_vendor-0.4.6-1/build/gz_physics_vendor-prefix/src/gz_physics_vendor/dartsim/src/GzCollisionDetector.cc:233:54:
    required from here
      233 |       rayHit.mNormal = Eigen::Vector3d(contact.normal);
          |                                                      ^
    /nix/store/0a944vkfl89hk2kzz36n5ywf8mgakr94-eigen-3.4.1/include/eigen3/Eigen/src/Core/Matrix.h:340:31: error: no
    matching function for call to 'Eigen::Matrix<double, 3, 1>::_init1<float [4]>(const float [4])'
      340 |       Base::template _init1<T>(x);
          |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~

[^1]: https://salsa.debian.org/games-team/ode/-/blob/e4a94122a0496dc1cb72d2cc7b5d54b4bf8a09ac/debian/rules#L13