Use fetchpatch2 with full_index=1 URLs everywhere
I noticed that building usb-cam results in hash mismatch in the needed
patch. The error message looked like this:

    building '/nix/store/772lzkrsqmyprd1zr8av2l3hhafn0g42-41805f7eb50f31e16839bb302df1bb5c6f30cb50.patch.drv'...
    structuredAttrs is enabled

    trying https://github.com/ros-drivers/usb_cam/commit/41805f7eb50f31e16839bb302df1bb5c6f30cb50.patch
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  1192 100  1192   0     0  4212     0  --:--:-- --:--:-- --:--:--  4226
    error: hash mismatch in fixed-output derivation '/nix/store/772lzkrsqmyprd1zr8av2l3hhafn0g42-41805f7eb50f31e16839bb302df1bb5c6f30cb50.patch.drv':
             specified: sha256-UXjqIHCkplBo5MWmH+ZlcRyy0IJgr8Qdld9QMq03SPI=
                got:    sha256-IKSzezNmy7qQzeo/eQJIiUMZ0KEbIr5CbUOOQkTpleo=
    error: Cannot build '/nix/store/di3pvvsrja65fs7xsg3dkl6lpdvvh6s1-ros-jazzy-usb-cam-0.8.1-r1.drv'.
           Reason: 1 dependency failed.
           Output paths:
             /nix/store/ajlplgm81knv3h8jkgd87rx1clxxf0yz-ros-jazzy-usb-cam-0.8.1-r1-debug
             /nix/store/nraxvmnymyaz3lgkjyjycx8qphnjfygp-ros-jazzy-usb-cam-0.8.1-r1

The reason is that github changes the length of commit hashes inside
the patches dynamically (see e.g.
https://github.com/NixOS/nixpkgs/issues/257446). The recommended way
to fetch patches seems to be using fetchpatch2 and appending
"?full_index=1" to the URL. See
https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#fetching-patches
This should guarantee the hash of the patch won't change.

For this reason, we convert all fetched patches to the recommended
form and update their hashes.

To check that this commit makes only the above mentioned changes, you
can use the following commands (when this commit is HEAD):

    sed -i -e 's/\?full_index=1//' $(git show --name-only --format="")
    git diff -U0 --color HEAD^|grep -vE '(hash =|fetchpatch)'

This will show in color (red and green) the other changes than the
above. As can be seen, it shows only the URLs that already had
"?full_index=1" in the past.