Migrate top-level Python packages to pyproject format
Evaluating Python packages against latest nixpkgs produces eval errors
like this:

    error: python3.13-rosdep-0.25.1 does not configure a `format`. To
    build with setuptools as before, set `pyproject = true` and
    `build-system = [ setuptools ]`.`

This is caused by commit:
https://github.com/NixOS/nixpkgs/pull/421660/commits/d2e9be2b076699b1a8e8d6b6f9ea4bebbd6956f9.

Here we fix all top-level packages with such an error.