flake.nix: Add "checks" flake output based on release.nix
To make "nix flake check" and similar tools work, we need to allow
setting the system attribute in release.nix explicitly. Without this,
flake jobs in Hydra complain about:

    error: attribute 'currentSystem' missing' in restricted evaluation mode.