workflows: Ensure that all vendored-source.json files are added to git
When adding a new ROS distro, new vendored-source.json files are
generated automatically by GitHub Actions. If we don't add them to
git, subsequent commit fails with error like:

    error: pathspec './distros/kilted/gz-plugin-vendor/vendored-source.json' did not match any file(s) known to git

The result is that no vendored-source.json updates are committed,
which is not what we want.