mavlink: Don't depend on python3Packages.future
This gets rid of the following error:

    error: future-1.0.0 not supported for interpreter python3.13